title: Top Blog
author: GitHub User
email: dashu-mnc@outlook.com
description: >
  This is a my page for TopBlog, I can write posts for this. You can read some posts.

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- github.md

footer_icons:
- username: toprise/blogs
  url: https://github.com/toprise/blogs/
  icon: icon-github.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
